---
name: local-llm-deployment
description: Use when planning local LLMs for mixed hardware.
version: 1.0.0
---

# Local LLM Deployment

Use this skill to assess a machine, recommend an appropriate local inference stack and model class, install only after approval, and verify the result. Treat a local model as a purpose-specific private/offline lane, not automatically a cloud-model replacement.

## 1. Gather facts before recommending

Obtain or verify:

- OS and architecture
- CPU core/thread count
- usable RAM
- GPU model and VRAM (do not treat a GPU name alone as proof of usable VRAM)
- free disk space
- intended use: interactive chat, private drafting, offline fallback, API service, or automated workload
- network exposure requirements

If the user supplies laptop specs remotely, state that those are reported specs rather than a live probe.

## 2. Choose the serving stack

| Hardware/use | Default stack |
|---|---|
| CPU-only server or low-VRAM laptop; single user | `llama.cpp` with GGUF |
| Windows desktop/laptop, user wants a GUI | LM Studio (GGUF) |
| NVIDIA GPU with enough VRAM; high-throughput service | vLLM, only after GPU/VRAM verification |

Do **not** recommend vLLM for a CPU-only VPS. Do not plan around a low-VRAM discrete GPU for substantial LLM inference.

## 3. Conservative sizing

Start with model class, not a specific model family:

- **3–4B Q4 GGUF:** suitable starting point for 16 GB RAM CPU-only machines; private drafting, simple summaries, fallback.
- **7–8B Q4/Q5:** only after evaluating CPU speed and RAM headroom; CPU-only systems will be materially slower.
- **12B+ or high-throughput serving:** requires verified GPU capacity; do not promise performance from system RAM alone.

Suggested compact models when compatible with current licensing and availability: Qwen 3–4B Instruct or Llama 3.x 3B Instruct, in `Q4_K_M` GGUF. Verify current Hugging Face availability and exact quant filename before installation.

## 4. Frame the result correctly

State explicitly:

- Local excels at private/offline drafting, lightweight transformations, and outage fallback.
- It is not a replacement for frontier cloud reasoning, fast autonomous coding, or large-context workloads on constrained hardware.
- Performance claims must be labeled as expected and hardware-dependent unless benchmarked locally.

## 5. Secure any VPS service

Default to localhost binding. If remote access is required, use authenticated private networking such as Tailscale; do not expose an unauthenticated inference endpoint to the public Internet. Confirm scope before changing firewall, services, or routing.

## 6. Installation and verification

Before installation: obtain explicit approval and confirm disk/RAM headroom.

After installation:

1. Launch the model service bound locally.
2. Submit a small completion/chat request to its API or GUI.
3. Confirm the response was generated by the local endpoint.
4. Report model name, quant, endpoint/binding, disk use, and observed result—not assumed success.

## Reference material

- `references/mixed-hardware-example.md` — verified planning example for a CPU VPS and a low-VRAM Windows laptop.
